language: groovy

sudo: false
# addons:
#   apt:
#     packages:
#       - oracle-java8-installer

jdk:
  - oraclejdk8

install: true

# NOTE: using git clone instead of gradle getGit for file order, causing problems on Travis with test class run order
before_script:
  - cd ..
  - git clone https://github.com/moqui/moqui-framework.git moqui
  - cd moqui
  - git clone https://github.com/moqui/moqui-runtime.git runtime
  - cd runtime/component
  - git clone https://github.com/moqui/mantle-udm.git
  - git clone https://github.com/moqui/mantle-usl.git
  - cd ../..
  - chmod +x gradlew

env:
  - TERM=dumb

script:
# using git commands instead:  - ./gradlew getGit -Pcomponent=mantle-usl
  - ./gradlew load
  - ./gradlew runtime/component/mantle-usl:test --info

cache:
  directories:
    - $HOME/.gradle/caches
    - $HOME/.gradle/wrapper
